condense_wildcard_suffixes  =  true
format_strings              =  true
imports_indent              =  "Block"
imports_layout              =  "Vertical"
indent_style                =  "Block"
merge_imports               =  true
normalize_comments          =  true
reorder_imports             =  true
use_try_shorthand           =  true
wrap_comments               =  true
