language: 'rust'

rust:

matrix:
  fast_finish: true

  include:
  - rust: 'nightly'
  - rust: 'beta'
  - rust: 'stable'

  allow_failures:
  - rust: 'nightly'

script:
  - 'cargo check'
  - 'cargo test'
