before_install:
  - sudo apt-get -y install build-essentials pkg-config libsdl2

language: 'rust'

rust:

matrix:
  fast_finish: true

  include:
  - rust: 'nightly'

script:
  - 'cargo check'
  - 'cargo test'
